[phases.setup]
nixPkgs = ['jdk17']

[phases.build]
cmds = ['chmod +x ./gradlew', './gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/expense-tracker-1.0.0.jar'