[phases.setup]
nixPkgs = ['...', 'jdk17']

[phases.build]
cmds = ['./gradlew clean bootJar --no-daemon --stacktrace']

[start]
cmd = 'java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar build/libs/expense-tracker-1.0.0.jar'